# o schema é a documentação do dbt 

models:
  - name: gold_vendas_7_dias
    description: " Tabela Gold que agreaga as vendas por produto nos últimos 7 dias, exibindo o total"
    columns:
      - name: data
        description: "Data da venda agreaga"
      - name: produto
        description: "Nome do produto vendido"
      - name: total_valor
        description: "Valor total da vendas do produto na data especificada"
      - name: total_quantidade
        description: "Quantidade total dos produtos vendidos na data especificada."
      - name: total_vendas
        description: "Número total de transações de vendas do produto na data especificada"
        
  - name: gold_vendas_por_vendador
    description: "Tabela Gold que agrega as vendas por vendedor nos últimos 7 dias, exibindo o dess"
    columns:
      - name: vendedor
        description: "Email do vendedor que realizou as vendas"
      - name: data 
        description: "Data das vendas agregadas por vendedor"
      - name: total_valor
        description: "Valor total das vendas realizadas peloo vendedor na data especificada."
      - name: total_quantidade
        description: "Quantidade total de produto vendidos pelo vendedor na data especificada"
      - name: total_vendas
        description: "Número total de transações realizadas pelo vendedorna data especificada"
